const allMeds = [
  {id:'D001',brand:'Dolo 650',generic:'Paracetamol',cat:'allopathy',use:'Fever/Pain'},
  {id:'D002',brand:'Crocin',generic:'Paracetamol',cat:'allopathy',use:'Fever/Pain'},
  {id:'D003',brand:'Combiflam',generic:'Ibuprofen+Paracetamol',cat:'allopathy',use:'Fever/Pain'},
  {id:'D004',brand:'Brufen',generic:'Ibuprofen',cat:'allopathy',use:'Pain/Inflammation'},
  {id:'D005',brand:'Voveran',generic:'Diclofenac',cat:'allopathy',use:'Joint Pain'},
  {id:'D006',brand:'Metformin',generic:'Metformin',cat:'allopathy',use:'Diabetes'},
  {id:'D007',brand:'Glycomet',generic:'Metformin',cat:'allopathy',use:'Diabetes'},
  {id:'D008',brand:'Glimepiride',generic:'Glimepiride',cat:'allopathy',use:'Diabetes'},
  {id:'D010',brand:'Amlodipine',generic:'Amlodipine',cat:'allopathy',use:'Blood Pressure'},
  {id:'D011',brand:'Telma',generic:'Telmisartan',cat:'allopathy',use:'Blood Pressure'},
  {id:'D012',brand:'Stamlo',generic:'Amlodipine',cat:'allopathy',use:'Blood Pressure'},
  {id:'D013',brand:'Atenolol',generic:'Atenolol',cat:'allopathy',use:'BP/Heart'},
  {id:'D014',brand:'Ecosprin',generic:'Aspirin',cat:'allopathy',use:'Blood Thinner'},
  {id:'D015',brand:'Warfarin',generic:'Warfarin',cat:'allopathy',use:'Blood Thinner'},
  {id:'D016',brand:'Atorvastatin',generic:'Atorvastatin',cat:'allopathy',use:'Cholesterol'},
  {id:'D017',brand:'Lipitor',generic:'Atorvastatin',cat:'allopathy',use:'Cholesterol'},
  {id:'D018',brand:'Rosuvastatin',generic:'Rosuvastatin',cat:'allopathy',use:'Cholesterol'},
  {id:'D019',brand:'Pantoprazole',generic:'Pantoprazole',cat:'allopathy',use:'Acidity/Ulcer'},
  {id:'D020',brand:'Omeprazole',generic:'Omeprazole',cat:'allopathy',use:'Acidity/Ulcer'},
  {id:'D022',brand:'Levothyroxine',generic:'Levothyroxine',cat:'allopathy',use:'Thyroid'},
  {id:'D023',brand:'Eltroxin',generic:'Levothyroxine',cat:'allopathy',use:'Thyroid'},
  {id:'D024',brand:'Sertraline',generic:'Sertraline',cat:'allopathy',use:'Depression'},
  {id:'D025',brand:'Fluoxetine',generic:'Fluoxetine',cat:'allopathy',use:'Depression'},
  {id:'D026',brand:'Alprazolam',generic:'Alprazolam',cat:'allopathy',use:'Anxiety'},
  {id:'D027',brand:'Clonazepam',generic:'Clonazepam',cat:'allopathy',use:'Anxiety/Seizure'},
  {id:'D028',brand:'Amoxicillin',generic:'Amoxicillin',cat:'allopathy',use:'Infection'},
  {id:'D029',brand:'Azithromycin',generic:'Azithromycin',cat:'allopathy',use:'Infection'},
  {id:'D030',brand:'Cetirizine',generic:'Cetirizine',cat:'allopathy',use:'Allergy'},
  {id:'D031',brand:'Allegra',generic:'Fexofenadine',cat:'allopathy',use:'Allergy'},
  {id:'D035',brand:'Prednisolone',generic:'Prednisolone',cat:'allopathy',use:'Inflammation/Asthma'},
  {id:'D036',brand:'Digoxin',generic:'Digoxin',cat:'allopathy',use:'Heart Failure'},
  {id:'D039',brand:'Clopidogrel',generic:'Clopidogrel',cat:'allopathy',use:'Blood Thinner'},
  {id:'D042',brand:'Insulin',generic:'Insulin',cat:'allopathy',use:'Diabetes'},
  {id:'D044',brand:'Tramadol',generic:'Tramadol',cat:'allopathy',use:'Pain'},
  {id:'D046',brand:'Phenytoin',generic:'Phenytoin',cat:'allopathy',use:'Epilepsy'},
  {id:'D048',brand:'Lithium',generic:'Lithium',cat:'allopathy',use:'Bipolar'},
  {id:'D049',brand:'Ciprofloxacin',generic:'Ciprofloxacin',cat:'allopathy',use:'Infection'},
  {id:'D050',brand:'Metronidazole',generic:'Metronidazole',cat:'allopathy',use:'Infection'},
  {id:'H001',brand:'Ashwagandha',generic:'Withania somnifera',cat:'siddha',use:'Stress/Energy'},
  {id:'H002',brand:'Triphala / திரிபலா',generic:'Triphala',cat:'siddha',use:'Digestion'},
  {id:'H003',brand:'Neem / வேம்பு',generic:'Azadirachta indica',cat:'siddha',use:'Skin/Blood'},
  {id:'H004',brand:'Turmeric / மஞ்சள்',generic:'Curcuma longa',cat:'siddha',use:'Inflammation'},
  {id:'H005',brand:'Tulsi / துளசி',generic:'Ocimum sanctum',cat:'siddha',use:'Cold/Immunity'},
  {id:'H006',brand:'Ginger / இஞ்சி',generic:'Zingiber officinale',cat:'siddha',use:'Nausea/Pain'},
  {id:'H007',brand:'Garlic / பூண்டு',generic:'Allium sativum',cat:'siddha',use:'Cholesterol/BP'},
  {id:'H008',brand:'Aloe Vera / கற்றாழை',generic:'Aloe barbadensis',cat:'siddha',use:'Skin/Digestion'},
  {id:'H009',brand:'Amla / நெல்லிக்காய்',generic:'Emblica officinalis',cat:'siddha',use:'Immunity'},
  {id:'H010',brand:'Cumin / சீரகம்',generic:'Cuminum cyminum',cat:'siddha',use:'Digestion'},
  {id:'H011',brand:'Brahmi / கோரோசன்',generic:'Bacopa monnieri',cat:'siddha',use:'Memory/Anxiety'},
  {id:'H012',brand:'Saffron / குங்குமப்பூ',generic:'Crocus sativus',cat:'siddha',use:'Depression/Memory'},
  {id:'H017',brand:'Fenugreek / வெந்தயம்',generic:'Trigonella foenum',cat:'siddha',use:'Diabetes/Digestion'},
  {id:'H019',brand:'Moringa / முருங்கை',generic:'Moringa oleifera',cat:'siddha',use:'Nutrition/Diabetes'},
  {id:'H020',brand:'Sarpagandha',generic:'Rauvolfia serpentina',cat:'siddha',use:'Blood Pressure'},
  {id:'H021',brand:'Guduchi / குடிலி',generic:'Tinospora cordifolia',cat:'siddha',use:'Immunity/Fever'},
  {id:'H023',brand:'Hibiscus / செம்பரத்தை',generic:'Hibiscus rosa',cat:'siddha',use:'BP/Cholesterol'},
  {id:'H024',brand:'Jamun / நாவல்',generic:'Syzygium cumini',cat:'siddha',use:'Diabetes'},
  {id:'H025',brand:'Curry Leaves / கருவேப்பிலை',generic:'Murraya koenigii',cat:'siddha',use:'Diabetes/Digestion'},
  {id:'H027',brand:'Shatavari / சதாவரி',generic:'Asparagus racemosus',cat:'siddha',use:'Hormonal Balance'},
  {id:'H030',brand:'Coriander / கொத்தமல்லி',generic:'Coriandrum sativum',cat:'siddha',use:'Digestion/Diabetes'},
];

const interactions = [
  {a:'D006',b:'H001',sev:'MODERATE',en:'Both lower blood sugar — hypoglycemia risk',ta:'இரண்டும் சர்க்கரையை குறைக்கும் — ரத்த சர்க்கரை அபாயகரமாக குறையலாம்',rec:'Doctor advice mandatory — monitor blood sugar closely'},
  {a:'D006',b:'H017',sev:'MODERATE',en:'Both lower blood sugar — hypoglycemia risk',ta:'வெந்தயமும் மெட்பார்மினும் சேர்ந்தால் சர்க்கரை மிகவும் குறையலாம்',rec:'Monitor blood sugar regularly — reduce fenugreek dose'},
  {a:'D006',b:'H019',sev:'MODERATE',en:'Moringa has antidiabetic effect — combined may over-lower sugar',ta:'முருங்கை சர்க்கரையை குறைக்கும் — சேர்த்து சாப்பிட்டால் அதிகமாக குறையலாம்',rec:'Use with caution — monitor blood sugar'},
  {a:'D006',b:'H024',sev:'MILD',en:'Jamun has mild antidiabetic effect — monitor sugar levels',ta:'நாவல் சர்க்கரையை சிறிது குறைக்கும் — கவனிக்கவும்',rec:'Monitor blood sugar — generally safe in small amounts'},
  {a:'D006',b:'H008',sev:'MODERATE',en:'Aloe vera lowers blood sugar — combined hypoglycemia risk',ta:'கற்றாழை சர்க்கரையை குறைக்கும் — சேர்ந்தால் மிகவும் குறையலாம்',rec:'Monitor blood sugar carefully'},
  {a:'D006',b:'D042',sev:'MODERATE',en:'Both lower blood sugar — hypoglycemia risk if doses not managed',ta:'இரண்டும் சர்க்கரையை குறைக்கும் — அளவு சரியாக வைக்க வேண்டும்',rec:'Only use together if doctor prescribed both — monitor sugar'},
  {a:'D007',b:'H001',sev:'MODERATE',en:'Both lower blood sugar — hypoglycemia risk',ta:'இரண்டும் சர்க்கரையை குறைக்கும் — கவனம் தேவை',rec:'Doctor advice mandatory — monitor blood sugar closely'},
  {a:'D015',b:'H007',sev:'SEVERE',en:'Garlic significantly increases bleeding risk with warfarin',ta:'பூண்டு ரத்தப்போக்கை மிகவும் அதிகரிக்கும் — ஆபத்து',rec:'Avoid combination — consult doctor immediately'},
  {a:'D015',b:'H004',sev:'SEVERE',en:'Turmeric/curcumin increases anticoagulant effect — severe bleeding risk',ta:'மஞ்சள் ரத்தப்போக்கை மிகவும் அதிகரிக்கும்',rec:'Avoid — dangerous combination'},
  {a:'D015',b:'H006',sev:'MODERATE',en:'Ginger has mild blood thinning effect — additive with warfarin',ta:'இஞ்சி ரத்தத்தை மெலிதாக்கும் — வார்பரினுடன் சேர்ந்தால் அபாயம்',rec:'Avoid or use minimal ginger — monitor INR'},
  {a:'D015',b:'H009',sev:'MODERATE',en:'Amla high Vitamin C may affect warfarin metabolism',ta:'நெல்லிக்காய் வார்பரின் வளர்சிதையை பாதிக்கலாம்',rec:'Monitor INR closely — consult doctor'},
  {a:'D014',b:'D015',sev:'DANGEROUS',en:'Two blood thinners together — life threatening bleeding risk',ta:'இரண்டு ரத்த மெலிதாக்கிகள் சேர்ந்தால் உயிருக்கு ஆபத்தான ரத்தப்போக்கு',rec:'Never combine without strict medical supervision'},
  {a:'D014',b:'H007',sev:'MODERATE',en:'Both thin blood — increased bleeding risk',ta:'இரண்டும் ரத்தத்தை மெலிதாக்கும் — ரத்தப்போக்கு அபாயம்',rec:'Avoid large amounts of garlic — consult doctor'},
  {a:'D014',b:'H006',sev:'MILD',en:'Mild additive blood thinning effect',ta:'இஞ்சி ரத்தத்தை மெலிதாக்கும் விளைவை கூட்டலாம்',rec:'Limit ginger intake — monitor for bruising'},
  {a:'D022',b:'H001',sev:'MODERATE',en:'Ashwagandha may alter thyroid hormone levels',ta:'அஸ்வகந்தா தைராய்டு அளவை மாற்றலாம்',rec:'Monitor thyroid levels regularly'},
  {a:'D023',b:'H001',sev:'MODERATE',en:'Ashwagandha may alter thyroid hormone levels',ta:'அஸ்வகந்தா தைராய்டு அளவை மாற்றலாம்',rec:'Monitor thyroid levels regularly'},
  {a:'D022',b:'H004',sev:'MILD',en:'Turmeric may reduce absorption of thyroid medicine',ta:'மஞ்சள் தைராய்டு மருந்தின் உறிஞ்சுதலை குறைக்கலாம்',rec:'Take thyroid medicine 4 hours apart from turmeric'},
  {a:'D022',b:'H017',sev:'MODERATE',en:'Fenugreek may interfere with thyroid hormone absorption',ta:'வெந்தயம் தைராய்டு மருந்தின் உறிஞ்சுதலை பாதிக்கலாம்',rec:'Take thyroid medicine on empty stomach — separate by 4 hours'},
  {a:'D024',b:'H012',sev:'MODERATE',en:'Both affect serotonin — serotonin syndrome risk',ta:'இரண்டும் மூளை வேதிப்பொருளை பாதிக்கும் — ஆபத்தான நிலை வரலாம்',rec:'Avoid combination — consult psychiatrist'},
  {a:'D024',b:'H011',sev:'MILD',en:'Brahmi may enhance sedative effects of sertraline',ta:'பிராமி மயக்க விளைவை அதிகரிக்கலாம்',rec:'Use with caution — monitor for excessive drowsiness'},
  {a:'D024',b:'D026',sev:'MODERATE',en:'CNS depression — excessive sedation and confusion',ta:'இரண்டும் மூளையை மந்தமாக்கும் — அதிக தூக்கம் குழப்பம்',rec:'Only use if prescribed together — monitor closely'},
  {a:'D010',b:'H023',sev:'MODERATE',en:'Hibiscus lowers BP — combined may cause dangerously low BP',ta:'செம்பரத்தை ரத்த அழுத்தத்தை குறைக்கும் — மிகவும் குறையலாம்',rec:'Monitor blood pressure closely'},
  {a:'D010',b:'H020',sev:'SEVERE',en:'Both lower BP significantly — dangerous hypotension risk',ta:'இரண்டும் ரத்த அழுத்தத்தை மிகவும் குறைக்கும் — மயக்கம் வரலாம்',rec:'Avoid combination — very dangerous'},
  {a:'D013',b:'H020',sev:'SEVERE',en:'Both lower heart rate and BP — life threatening combination',ta:'இரண்டும் இதய துடிப்பையும் ரத்த அழுத்தத்தையும் குறைக்கும்',rec:'Absolutely avoid — life threatening'},
  {a:'D026',b:'H011',sev:'MODERATE',en:'Both have sedative effects — excessive drowsiness risk',ta:'இரண்டும் மயக்கம் தரும் — அதிக தூக்கம் வரலாம்',rec:'Avoid combination — dangerous drowsiness'},
  {a:'D026',b:'H001',sev:'MODERATE',en:'Ashwagandha enhances sedative effect of alprazolam',ta:'அஸ்வகந்தா மயக்க விளைவை அதிகரிக்கும்',rec:'Use with caution — reduce dose if needed'},
  {a:'D039',b:'H007',sev:'SEVERE',en:'Both prevent clotting — severe life threatening bleeding risk',ta:'இரண்டும் ரத்தம் உறையாமல் செய்யும் — உயிருக்கு ஆபத்தான ரத்தப்போக்கு',rec:'Avoid — consult cardiologist immediately'},
  {a:'D035',b:'D006',sev:'MODERATE',en:'Steroids raise blood sugar — counteracts metformin',ta:'ஸ்டீராய்டு சர்க்கரையை ஏற்றும் — மெட்பார்மினை எதிர்க்கும்',rec:'Monitor blood sugar closely during steroid course'},
  {a:'D016',b:'H007',sev:'MILD',en:'Garlic may mildly enhance cholesterol lowering effect',ta:'பூண்டு கொழுப்பு குறைக்கும் விளைவை கூட்டலாம்',rec:'Generally safe — monitor liver enzymes'},
];
